# DotNet test CI pipeline

name: DotNET Tests

on:
  push:
    branches: 
      - main
    paths:
      - dotnet/**
      - .github/workflows/dotnet-tests.yml

jobs:
  dotnet-build:
    name: .Net Build

    runs-on: windows-latest

    defaults:
      run:
        working-directory: ./dotnet/CJson

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
    
    - name: Check
      run: |
        cd ./CJson/bin/Release
        dir

    - name: Artifact store
      uses: actions/upload-artifact@v3
      with:
        name: .Net_nuget
        path: ./dotnet/CJson/CJson/bin/Release

  dotnet-test:
    needs: dotnet-build
    name: .Net Test

    runs-on: windows-latest

    defaults:
      run:
        working-directory: ./dotnet/CJson

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Test
        run: dotnet test CJsonTests/CJsonTests.csproj --no-build --verbosity normal
