# Java test CI pipeline

name: Java Tests

on:
  push:
    branches:
      - main
    paths:
      - java/**
      - .github/workflows/java-tests.yml

jobs:
  
  java-build:
    name: Java build
    runs-on: windows-latest

    defaults:
      run:
        working-directory: ./java/Coded-Json

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Check
      run: |
        cd ./target
        dir
    
    - name: Artifact store
      uses: actions/upload-artifact@v3
      with:
        name: Java_build
        path: ./java/Coded-Json/target
  
  java-test:
    needs: java-build

    name: Test
    runs-on: windows-latest

    defaults:
      run:
        working-directory: ./java/Coded-Json

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
          
      - name: Test
        run: mvn test