# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./npm
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - run: npm i
        
        name: Building source
      - run: npm run build
      - run: dir
      - uses: actions/upload-artifact@v3
        with:
          name: Tarbal store
          path: ./coded-json-[0-9].[0-9].[0-9].tgz