name: Pages Deploy
on: 
  push:
    branches:
      - main
    paths:
      - .github/workflows/pages-deploy.yml

permissions:
  contents: write

jobs:
  setup:
    name: Environment Setup
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      
      - name: Run document generator
        run: ./document_generator.bat
        shell: cmd

      - name: Check
        working-directory: ./docs
        run: dir
      
      - name: Push files
        run: |
          git status
          git config --global user.name "SubhenduShekhar"
          git config --global user.email "subhendushekhargupta@gmail.com"
          git fetch
          git pull origin docs
          git switch docs
          git add .
          git commit -m "push files in docs"
          git push origin docs