# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created

name: Tests

on:
  push:
    branches:
      - main

jobs:
  npm-build:
    name: NPM Build
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./npm
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - run: npm i
        
        name: Building source
      - run: npm run build
      - run: dir

      - uses: actions/upload-artifact@v3
        with:
          name: Tarbal_store_npm
          path: ./npm/coded-json-*.tgz

  python-build:
    name: Python build
    runs-on: windows-latest

    defaults:
      run:
        working-directory: ./python
      
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Build package
      run: python setup.py sdist
    
    - name: Artifact store
      uses: actions/upload-artifact@v3
      with:
        name: Tarbal_store_python
        path: ./python/dist/codedjson-*.tar.gz
  
  npm-test:
    needs: npm-build
    name: Test
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./tests/npm
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      
        name: Loading tar
      - uses: actions/download-artifact@v3
        with:
          name: Tarbal_store_npm
          path: ./tests/npm
      - run: dir
      - run: npm i

        name: Running tests
      - run: npm run test
    
  python-test:
    needs: python-build
    name: Test
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./tests/python
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      
      - name: Loading tar
        uses: actions/download-artifact@v3
        with:
          name: Tarbal_store_python
          path: ./tests/python
        
      - run: |
          dir
          pip install -r requirements.txt
        
      - name: Running Tests
        run: python cjson_tests.py